FarmasiaVR/farmasia-vr

- Assets/Prefabs/FireSafety/EmergencyExit.prefab
- Assets/Prefabs/SharedPrefabsBetweenAsepticAndFireSafety/Door.prefab
- Assets/Prefabs/SharedPrefabsBetweenAsepticAndFireSafety/DoorSign.prefab
The changes here should be very safe, but I'm waiting for someone else to confirm that there was z-fighting/flickering before this PR. I just changed the door sign z position by -0.01 and for me that fixed door signs flickering.
> Fix z-fighting/flickering door signs

- Assets/AshVFX.vfx
- Assets/Prefabs/FireSafety/ExtinguishParticlesVFX.prefab
- Assets/Prefabs/FireSafety/FireGridObject.prefab
- Assets/Prefabs/FireSafety/Smoke.prefab
- Assets/Prefabs/SharedPrefabsBetweenAsepticAndFireSafety/MainMenu/EmergencyExitButton Variant.prefab
- Assets/Samples/Visual Effect Graph/12.1.8/VisualEffectGraph Additions/VFX/Smoke.vfx
> Ash and smoke

- Assets/Scripts/PlayerBurn.cs
- Assets/Scripts/PlayerBurn.cs.meta
The player can now burn in the fire and will die if standing in it for too long
> Health test

- Assets/Prefabs/FireSafety/FireArea.prefab
- Assets/Prefabs/FireSafety/FireArea.prefab.meta
- Assets/Scripts/Utilities/PlayerOnFireManager.cs
- Assets/_Scenes/EmergencyExitScenes/EmergencyExit 1.unity
- Assets/_Scenes/EmergencyExitScenes/EmergencyExit.unity
> Escape scene layouts

- Assets/Prefabs/FireSafety/ExtinguisherWithFoam.prefab
- Assets/Prefabs/FireSafety/ExtinguisherWithHoseAndPin.prefab
- Assets/Prefabs/FireSafety/Eye shower.prefab
- Assets/Prefabs/FireSafety/EyeWashBottle.prefab
- Assets/Prefabs/FireSafety/FireBlanket.prefab
- Assets/Prefabs/FireSafety/XR Player (with snap turning).prefab
- ProjectSettings/TagManager.asset
- Add grabbable layer (TP raycast will ignore this layer)
- Set layer to grabbable for all grabbable objects
- Make teleport raycasts ignore grabbable objects (grabbable layer)
> Make teleportation work better when holding an object in hand

- Assets/Samples/Visual Effect Graph/12.1.8/VisualEffectGraph Additions/VFX/Fire.vfx
- Assets/Samples/Visual Effect Graph/12.1.8/VisualEffectGraph Additions/VFX/SpreadableFire.vfx
- Assets/Scripts/ExtingushSpreadableFire.cs
- Assets/Scripts/ExtingushSpreadableFire.cs.meta
- Assets/Scripts/SpreadableFire.cs
- Assets/_Scenes/FireSafetyTutorials/SpreadableFireTest.unity
Extinguishing spreadable fire by sphere casting from a extinguisher
> Extingushing spreadable fire

- Assets/AddressableAssetsData/AssetGroups/Localization-Assets-Shared.asset
- Assets/AddressableAssetsData/AssetGroups/Localization-Locales.asset
- Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-English (en).asset
- Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-Finnish (fi).asset
- Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-Swedish (sv).asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod Shared Data.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Assets/Packages/SimpleHands/Materials/White-Hand.mat
- Assets/Packages/XR/Settings/OpenVRSettings.asset
- Assets/Prefabs/PlateCountMethod/XR Player (with snap turning).prefab
- Assets/Prefabs/SharedPrefabsBetweenAsepticAndFireSafety/XR Player.prefab
- Assets/Scripts/Objects/GeneralItem.cs
- Assets/Scripts/PlateCountMethod/CabinetBasePCM.cs
- Assets/Scripts/PlateCountMethod/CabinetBasePCM_Old.cs
- Assets/Scripts/PlateCountMethod/CabinetBasePCM_Old.cs.meta
- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
- Assets/Task Lists/PlateCountMethodTasks.asset
- Assets/XR/Settings/Open VR Settings.asset
- Assets/XR/Settings/OpenXR Editor Settings.asset
- ProjectSettings/ProjectSettings.asset
This version has a quest for puting tools to the cabinet. The actual tools are missing. Needs to be tested with meta quest.
> Tools to cabinet

- Assets/Prefabs/AsepticSpace/Sabouraud XR plate.prefab
- Assets/Prefabs/AsepticSpace/Soija-kaseiini XR.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/BlueStickInCover XR.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/BlueStickInCover XR.prefab.meta
- Assets/Scripts/Objects/LiquidContainer.cs
- Assets/Scripts/PlateCountMethod/CabinetBasePCM.cs
- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
1. Removed old pipette and replaced it with a pipettor and a small pipette
2. Pipettor transfers 0,5ml at a time
3. Player can fill tubes with phosphate. Task is completed when one control tube has 1 ml and three other tubes have 4,5ml
4. Nothing happens if player puts phosphate to senna tube (maybe it would be a mistake?)
5. Tubes can be filled at any time yet to make testing easier (to be changed in future so it is only possible in laminar cabinet after previous step is done)
6. Added one line of code to LiquidContainer.cs so it would trigger liquid amount changing event also when liquid is transferred away from test tube
1. Deleted script component from new pass through cabinet because it spammed errors to the log and is unnecessary in this scenario
> FVR-105: fill test tubes with phosphate

- Assets/Localization/LocalSettings/Tables/XR MembraneFilteration 2.0_fi.asset
- Assets/Prefabs/AsepticSpace/AutomaticPipette XR.prefab
- Assets/Prefabs/AsepticSpace/Sabouraud XR plate.prefab
- Assets/Scripts/Objects/Equipment/Cover.cs
- Assets/_Scenes/ControlsTutorial.unity
Fixes:
- FVR-144
- FVR-132
- FVR-131
- FVR-139
- FVR-155
All changes fully playtested in VR.
> Several bug fixes

- Assets/Scripts/Interactables/DragAcceptable.cs
- Assets/Scripts/Objects/Equipment/WritingPen.cs
- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
- Assets/Task Lists/PlateCountMethodTasks.asset
1. Player can complete the new task by writing dilution proportions or control onto test tubes
2. Writing options are updated
1. Fixed a warning in the logs which complained about changing linear velocity for kinematic rigidbodies
2. Fixed a warning in the logs which complained about unnecessary canvas renderer component (removed the component)
> FVR-103: Serial dilution preparation

- Assets/Localization/LocalSettings/Tables/ControlsTutorial_sv.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod Shared Data.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Assets/Scripts/Managers/HintManager.cs
- Assets/Scripts/Utilities/HintBoxNew.cs
Changes to get localization working and adding text to current tasks.
> FVR-117 localization and translations

- Assets/Localization/LocalSettings/Tables/PlateCountMethod Shared Data.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Assets/Scripts/PlateCountMethod/CabinetBasePCM.cs
- Assets/Scripts/Utilities/HintBoxNew.cs
Added localization for putting dirty items in the cabinet, opening the hintbox and writing on test tubes.
> Localization for various parts.

- Assets/BigPipetteXR.cs
- Assets/Localization/LocalSettings/Tables/PlateCountMethod Shared Data.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Assets/Scripts/Interactables/GUIConsole.cs
- Assets/Scripts/PlateCountMethod/CabinetBasePCM.cs
- Added a consolescreen into the game
- Added localization to breaking the pipettor and got the message to show up
- Items now get cleaned when added into the laminar flow cabinet, after getting a message of them being dirty.
> Localization and small tweaks

- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
Reverts FarmasiaVR/farmasia-vr#67
> Revert "Fvr 223 skip merge"

- Docs/build.md
Added info about `ovr-platform-util` to build documentation
> Docs: Include section on Meta Store CLI

- Assets/Scripts/PlateCountMethod/showLiquidContainerLiquidAmountPCM.cs
Added variable to the Liquid Display which can be used to modify the amount of liquid a display shows. Senna tube display now shows zero with 1ml of liquid inside.
No known issues.
> Fvr 240 senna shows zero

- ProjectSettings/DynamicsManager.asset
Tested in PCM scene that no object had collision with writing options. Completed writing task successfully.
> FVR-235: Disabled collision between UI and objects

- Assets/Scripts/Objects/NewConnectionSystem/PipetteContainer.cs
- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
New branch for FVR-164 since the old branch broke everything when trying to merge. Added a mistake when transferring liquid with the same pipette in preparation and serial dilution.
> Fvr 164 mistake same pipette v2

- Assets/Localization/LocalSettings/Tables/PlateCountMethod Shared Data.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Assets/Prefabs/PlateCountMethod/MoveItemsButton.prefab
- Assets/Prefabs/PlateCountMethod/MoveItemsButton.prefab.meta
- Assets/Prefabs/PlateCountMethod/metaltable (1).prefab
- Assets/Prefabs/PlateCountMethod/metaltable (1).prefab.meta
- Assets/Scripts/PlateCountMethod/MoveItemsToTablePCM.cs
- Assets/Scripts/PlateCountMethod/MoveItemsToTablePCM.cs.meta
- Added a button inside the cabinet,
- Button teleports all items to the side table,
- Button is removed after pressing it.
- Button is also removed after completing task toolsToCabinet.
- Button has localization.
- A commit where breaking the pipetor is reverted to unity events.
Because of mergeconflict errors when trying to get the most recent pushes into the branch, I had to make another branch, that only has my changes on top of the most recent dev. Tested in VR.
> Button that moves items to side table

- Assets/Scripts/Utilities/HintBoxNew.cs
- Assets/Tests/ProgressSystemTests/HintManagerTests.cs
Removed mistake caused by opening a hintbox.
> FVR-239 Removed mistake when opening hintbox

- Assets/Prefabs/PlateCountMethod/Equipment/Sabouraud XR plate PCM.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/SoyCasein XR plate PCM.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/bluestick_new.prefab
- Assets/Scripts/Objects/Equipment/AgarPlateBottom.cs
- Assets/Scripts/Objects/Equipment/Pipette.cs
- Assets/Scripts/Objects/LiquidContainer.cs
- Assets/Scripts/Objects/SpreadStick.cs
This PR introduces mistake events for incorrect tool usage, enhances feedback with a success sound, and includes minor fixes to improve the user experience.  
- **Contaminated Pipette Mistake** ([FVR-199])  
- A mistake event is now triggered when a **contaminated Finn pipette** is used on a liquid with a different concentration.  
- **Contaminated Stick Mistake** ([FVR-203])  
- A mistake event is now triggered when a **contaminated stick** is used on a different liquid.  
- A **success sound** is now played when the **spreading status changes to "complete"** to provide clearer feedback.  
- **Fixed Blue Stick Grip** _(Not in Jira)_  
- Adjusted the **blue stick’s grip position** so it sits correctly in VR.  
- **Fixed Liquid Contamination Bug** _(Not in Jira)_  
- Resolved an issue …
> Fvr 199 adding mistakes

- Assets/Prefabs/PlateCountMethod/Equipment/Sabouraud XR plate PCM.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/SoyCasein XR plate PCM.prefab
- Assets/Scripts/Objects/Equipment/AgarPlateBottom.cs
- Assets/Scripts/Objects/Equipment/AgarPlateVent.cs
- Assets/Scripts/Objects/Equipment/AgarPlateVent.cs.meta
- Created a new script AgarPlateVent.cs which controls opening the lid a little bit for ventilation. The script is added to XR plate PCM prefabs to their agarplatelid game objects
- Venting is activated by pressing activate while holding an agar plate bottom in hand
- AgarPlateVent has a public boolean which indicates whether the plate is currently venting or not
> FVR-236: Vent mechanism for agar plates

- Assets/Prefabs/AsepticSpace/Actually working pipette XR.prefab
- Assets/Prefabs/PlateCountMethod/SmallGarbageCan.prefab
- Assets/Prefabs/SharedPrefabsBetweenAsepticAndFireSafety/HintBoxNew.prefab
- Finnpipette has a new collider for the pipette head which allows the pipette to enter small objects. This fixes the spinning issue, which was caused by colliders trying to find a way around one another.
- Added the hint box to the UI layer which disables collisions with most object types.
> Fvr 271 finnpipette carousel

- Assets/Prefabs/PlateCountMethod/Equipment/Sabouraud XR plate PCM.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/SoyCasein XR plate PCM.prefab
- Assets/Scripts/Objects/Equipment/AgarPlateBottom.cs
- Removed audio sources from agar plates and code that activated them in `AgarPlateBottom`
- Added SFX Manager calls to `OnSpreadingComplete` events in agar plates
Tested in simulator
> FVR-282: Agar SFX fix

- Assets/Prefabs/PlateCountMethod/Equipment/pipette_box.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/pipette_box.prefab.meta
- Finnpipette box is now a prefab
- Finnpipette box layer changed to SmallObject
> FVR-284: Finnpipette box UI collision

- Assets/Scripts/PlateCountMethod/CabinetBasePCM.cs
- Assets/Scripts/PlateCountMethod/SkipCurrentTaskPCM.cs
- Assets/Scripts/PlateCountMethod/SkipCurrentTaskPCM.cs.meta
- Assets/Scripts/PlateCountMethod/pipette_box.cs
- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
- Skip for WriteOnTubes task
- Refactored skipping to a new file
- FillTubes skip now fills existing tubes
- Fixed Finnpipette box to accept the skip pipette also
> Donut skip update

- Assets/Localization/LocalSettings/Tables/ControlsTutorial_sv.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod Shared Data.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Assets/Scripts/Managers/MixingManager.cs
- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
- Assets/Scripts/UISystem/WritingOptions/WritingOptions.cs
- Removed max number of rows error message while writing.
- Added localization for the popup that occurs when writing the same dilution type on for example test tubes.
- Fixed some Swedish translations in controls tutorial
- Added game mechanics into hintboxes in PCM
Tested in VR
> Fvr 305 and 301 and localization

- Assets/Localization/LocalSettings/Tables/PlateCountMethod Shared Data.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Added "Well spread"
- Changed "ilmasta mailja" to "Haihduta ylimääräinen neste maljoista"
- localization for both.
Changes only in localization tables, so not tested.
> localization changes for ventilation.

- Assets/Prefabs/PlateCountMethod/Equipment/Sabouraud XR plate PCM.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/SoyCasein XR plate PCM.prefab
- Assets/Scripts/Objects/Equipment/AgarPlateVent.cs
- Changed the parent of `LidRotate` from lid to the bottom to prevent it from moving around with the lid
- Also fixed a bug when the plate would not send the event `onVentingChanged` when ventilation process has been stopped by opening the whole lid
Did not encounter the bug when venting repeatedly and switching lids of different plates.
> FVR-324: Fixed weird lid behavior when ventilating

- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
- Added a check to ensure that the liquid is in the dictionary of allowed liquids
Tested that changes worked, and you still can transfer allowed liquids
> FVR-335: Cannot transfer Senna or other unrelated liquids to agar plates

- Assets/Resources/Prefabs/HintBox.prefab
- Assets/_Visuals/Textures/RenderTextures/BottleLabel7.renderTexture
- Assets/_Visuals/Textures/RenderTextures/BottleLabel7.renderTexture.meta
- Assets/_Visuals/Textures/RenderTextures/BottleLabel8.renderTexture
- Assets/_Visuals/Textures/RenderTextures/BottleLabel8.renderTexture.meta
- Assets/_Visuals/Textures/RenderTextures/Materials/BottleLabel7.mat
- Assets/_Visuals/Textures/RenderTextures/Materials/BottleLabel7.mat.meta
- Assets/_Visuals/Textures/RenderTextures/Materials/BottleLabel8.mat
- Assets/_Visuals/Textures/RenderTextures/Materials/BottleLabel8.mat.meta
- 2 new materials, 1 for each bottle
- New render textures for each new material
- 4 new cameras, 1 for each new 100ml bottle
- Connected cameras to bottles in scene
- Moved a couple of items in the passthrough cabinet for cleaner look and gameplay
- Removed extra hintboxes
- Yes
- No new bugs or issues introduced
> Fvr 62 membrane filtration spare parts

- Assets/Localization/LocalSettings/Tables/PlateCountMethod_en.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_fi.asset
- Assets/Localization/LocalSettings/Tables/PlateCountMethod_sv.asset
- Assets/Scripts/PlateCountMethod/BoxController.cs
- Now soy casein is put into 37C incubator and sabouraud into 25C
- Fixed some typos in translations and removed dots at the end of sentences for uniformity
> FVR-360: Swap plates needed for incubation

- Assets/Prefabs/PlateCountMethod/Equipment/Sabouraud XR plate PCM.prefab
- Assets/Prefabs/PlateCountMethod/Equipment/SoyCasein XR plate PCM.prefab
- Assets/Scripts/Objects/AgarMaterialChange.cs
- Assets/Scripts/Objects/AgarMaterialChange.cs.meta
- Script is controlled through events in the agar plate bottom
- Agar plate bottom Liquid container onLiquidTransfer triggers method for changing material color and smoothness. It makes the agar darker and shinier.
- Agar plate bottom onSpreadingComplete triggers method for changing material smoothness. It makes the agar less shiny.
- Agar plate bottom now has an ObjectType, SoyCaseine or Sabouraud.
- These changes are also added on the prefabs.
- No new bugs found.
> Fvr 330 agar plate liquid indicator

- Assets/Scripts/Managers/PopupManager.cs
- Assets/Scripts/PlateCountMethod/PopupManagerPCM.cs
- Assets/Scripts/UISystem/Components/PointPopup.cs
Changed notifications so that they don't overlap but stack on top of eachother. This helps with readability
> Fvr 337 stacking notifs

- Assets/BigPipetteXR.cs
- Assets/Scripts/Objects/Equipment/Cover.cs
- Assets/Scripts/Objects/SpreadStick.cs
- Assets/Scripts/SceneManagers/PlateCountMethodSceneManager.cs
- Assets/Task Lists/PlateCountMethodTasks.asset
Also remove debug log line, and add scorescreen setActive() function to scene manager
> Update points given for tasks and mistakes
